# Generated by Django 3.0.7 on 2021-10-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.IntegerField(max_length=10)),
                ('gender', models.CharField(max_length=25)),
                ('msg', models.TextField()),
            ],
        ),
    ]
